"""Cambiar sale_number a String y restricción única por date

Revision ID: 2fe5b6d4b63a
Revises: 
Create Date: 2025-02-16 01:50:06.634748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fe5b6d4b63a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('sale_number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=3),
               existing_nullable=False)
        batch_op.drop_constraint('unique_sale_per_business_per_year', type_='unique')
        batch_op.create_unique_constraint('unique_sale_per_business_per_year', ['business_id', 'sale_number', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint('unique_sale_per_business_per_year', type_='unique')
        batch_op.create_unique_constraint('unique_sale_per_business_per_year', ['business_id', 'sale_number', 'year'])
        batch_op.alter_column('sale_number',
               existing_type=sa.String(length=3),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
