"""Add new field to RawMaterial model

Revision ID: 5260acb1f2ab
Revises: 4a2b7a230353
Create Date: 2025-02-21 14:53:06.422735

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5260acb1f2ab"
down_revision = "4a2b7a230353"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("raw_material", schema=None) as batch_op:
        batch_op.add_column(sa.Column("sku", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("min_stock", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("expiration_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("created_at", sa.DateTime(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "updated_at",
                sa.DateTime(),
                nullable=True,
                on_update=sa.text("CURRENT_TIMESTAMP"),
            )
        )
        batch_op.create_unique_constraint("uq_raw_material_sku", ["sku"])

    with op.batch_alter_table("sale_product", schema=None) as batch_op:
        batch_op.alter_column("quantity", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sale_product", schema=None) as batch_op:
        batch_op.alter_column("quantity", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("raw_material", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("updated_at")
        batch_op.drop_column("created_at")
        batch_op.drop_column("expiration_date")
        batch_op.drop_column("min_stock")
        batch_op.drop_column("sku")

    # ### end Alembic commands ###
