"""Fix issues in Sale model

Revision ID: 7a4b83ac8703
Revises: ed49975f7f8b
Create Date: 2025-02-22 01:56:00.390452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a4b83ac8703'
down_revision = 'ed49975f7f8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('discount',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('tax',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('total_amount',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_constraint('unique_sale_per_business_per_date', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_sale_per_business_per_date', ['business_id', 'sale_number', 'date'])
        batch_op.alter_column('total_amount',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('tax',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('discount',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('payment_method',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###
