"""Eliminar columna year y cambiar nombre a la restriccion unique

Revision ID: 7aa960eec286
Revises: 2fe5b6d4b63a
Create Date: 2025-02-16 01:54:17.199464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aa960eec286'
down_revision = '2fe5b6d4b63a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_constraint('unique_sale_per_business_per_year', type_='unique')
        batch_op.create_unique_constraint('unique_sale_per_business_per_date', ['business_id', 'sale_number', 'date'])
        batch_op.drop_column('year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint('unique_sale_per_business_per_date', type_='unique')
        batch_op.create_unique_constraint('unique_sale_per_business_per_year', ['business_id', 'sale_number', 'date'])

    # ### end Alembic commands ###
