"""Create new models for Account Classifier

Revision ID: 852acd6d6187
Revises: 909bad5af3ae
Create Date: 2025-02-24 00:36:10.676263

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "852acd6d6187"
down_revision = "909bad5af3ae"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ac_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "ac_sub_account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_code", sa.String(length=20), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_code"],
            ["ac_account.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "ac_element",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("subaccount_code", sa.String(length=20), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["subaccount_code"],
            ["ac_sub_account.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sale", schema=None) as batch_op:
        batch_op.alter_column(
            "subtotal_amount", existing_type=sa.FLOAT(), nullable=False
        )

    with op.batch_alter_table("ac_element", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "unique_ac_element_code_per_ac_subaccount_code", ["code", "subaccount_code"]
        )

    with op.batch_alter_table("ac_sub_account", schema=None) as batch_op:
        batch_op.create_unique_constraint(
            "unique_ac_subaccount_code_per_ac_account_code", ["code", "account_code"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sale", schema=None) as batch_op:
        batch_op.alter_column(
            "subtotal_amount", existing_type=sa.FLOAT(), nullable=True
        )

    op.drop_table("ac_element")
    op.drop_table("ac_sub_account")
    op.drop_table("ac_account")
    # ### end Alembic commands ###
