"""Add batch preparation to Product model

Revision ID: 8c0d4d5c7f12
Revises: c293d1976e6e
Create Date: 2025-03-01 19:40:28.021639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0d4d5c7f12'
down_revision = 'c293d1976e6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_batch_prepared', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('batch_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('batch_size')
        batch_op.drop_column('is_batch_prepared')

    # ### end Alembic commands ###
