"""Add subtotal_amount to Sale model

Revision ID: 909bad5af3ae
Revises: 7a4b83ac8703
Create Date: 2025-02-22 13:21:31.515768

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "909bad5af3ae"
down_revision = "7a4b83ac8703"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sale", schema=None) as batch_op:
        batch_op.add_column(sa.Column("subtotal_amount", sa.Float(), nullable=True))

    with op.batch_alter_table("sale_product", schema=None) as batch_op:
        batch_op.alter_column("quantity", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column("unit_price", existing_type=sa.FLOAT(), nullable=False)
        batch_op.alter_column("total_price", existing_type=sa.FLOAT(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sale_product", schema=None) as batch_op:
        batch_op.alter_column("total_price", existing_type=sa.FLOAT(), nullable=True)
        batch_op.alter_column("unit_price", existing_type=sa.FLOAT(), nullable=True)
        batch_op.alter_column("quantity", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("sale", schema=None) as batch_op:
        batch_op.drop_column("subtotal_amount")

    # ### end Alembic commands ###
