"""Add new field to Sale model

Revision ID: b14889ea2ef0
Revises: f7eb3edfae84
Create Date: 2025-02-21 14:40:09.162626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b14889ea2ef0'
down_revision = 'f7eb3edfae84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tax', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_column('tax')
        batch_op.drop_column('discount')
        batch_op.drop_column('customer_name')
        batch_op.drop_column('status')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
