"""Add new field to Sale model

Revision ID: ed49975f7f8b
Revises: 5260acb1f2ab
Create Date: 2025-02-21 15:23:37.568587

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ed49975f7f8b"
down_revision = "5260acb1f2ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sale", schema=None) as batch_op:
        batch_op.add_column(sa.Column("total_amount", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sale", schema=None) as batch_op:
        batch_op.drop_column("total_amount")

    # ### end Alembic commands ###
