"""Add new field to Product model

Revision ID: f7eb3edfae84
Revises: b17462c954a5
Create Date: 2025-02-21 13:04:27.406862

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f7eb3edfae84"
down_revision = "b17462c954a5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.add_column(sa.Column("description", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("category", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("sku", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("barcode", sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column("unit", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("is_active", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("min_stock", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("cost_price", sa.Float(), nullable=True))
        batch_op.create_unique_constraint("uq_product_sku", ["sku"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("cost_price")
        batch_op.drop_column("min_stock")
        batch_op.drop_column("is_active")
        batch_op.drop_column("unit")
        batch_op.drop_column("barcode")
        batch_op.drop_column("sku")
        batch_op.drop_column("category")
        batch_op.drop_column("description")

    # ### end Alembic commands ###
